<a href="https://colab.research.google.com/github/Prakface/Practice/blob/master/Appending_training_wts_data_Loader_Actual_Labels2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import math
from torch.autograd import Variable


url='https://raw.githubusercontent.com/Prakface/Practice/master/One_mon_present_full.csv'

url2='https://raw.githubusercontent.com/Prakface/Practice/master/Final_one_month_prev_features.csv'

url_h='https://raw.githubusercontent.com/Prakface/Practice/master/heuristic_labels.csv'

data = pd.read_csv(url) 

data2= pd.read_csv(url2)

print("Data Shape:", data.shape) 

#data=pd.read_csv(url)

df=pd.DataFrame(data)
print(data.head()) 


data_modified= data.dropna()

data_modified.to_csv("modifiedData.csv", index=False)


df2=pd.read_csv("modifiedData.csv")

print(df2[0:6])

print(df2['result'])

df_main=df2[df2.columns[~df2.columns.isin(['text', 'user_name'])]]

print(df_main.columns)

print(len(df_main.columns))

  
# X_1, y_1 means rpesent tweets' data
X_1=df_main[df_main.columns[~df_main.columns.isin(['time', 'tweet_id','result'])]] #removing result attribute as it is class label, hence we get 34 attributes
X_1=X_1.iloc[:,1:len(X_1.columns)].values   #removing the unnamed attribute
x_1=df_main[df_main.columns[~df_main.columns.isin(['time', 'tweet_id','result'])]]
x_1=x_1.iloc[:,1:len(x_1.columns)].values 
y_1=df_main.loc[:, ['result']].values


print(type(X_1), type(y_1), type(x_1), type(y_1))

print(X_1.shape)
print(y_1.shape)




Data Shape: (1908, 40)
  Unnamed: 0 cat1  cat10  ...      tweet_id  url      user_name
0          0    0      0  ...  8.323790e+17  0.0  THEJEROMEOWEN
1          1    0      0  ...  8.323786e+17  0.0       Acejinjo
2          2    0      0  ...  8.323780e+17  0.0     RabRakha21
3          3    0      0  ...  8.323777e+17  0.0       RS_Aloha
4          4    0      0  ...  8.323767e+17  0.0  preciselyizzy

[5 rows x 40 columns]
   Unnamed: 0  cat1  cat10  ...      tweet_id  url        user_name
0           0     0      0  ...  8.323790e+17  0.0    THEJEROMEOWEN
1           1     0      0  ...  8.323786e+17  0.0         Acejinjo
2           2     0      0  ...  8.323780e+17  0.0       RabRakha21
3           3     0      0  ...  8.323777e+17  0.0         RS_Aloha
4           4     0      0  ...  8.323767e+17  0.0    preciselyizzy
5           5     0      0  ...  8.323759e+17  0.0  thefireistarted

[6 rows x 40 columns]
0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
5       1.0

In [0]:
data2= pd.read_csv(url2)

print("Data Shape:", data2.shape) 

#data=pd.read_csv(url)

df_prev=pd.DataFrame(data2)
print(data2.head()) 


data2_modified= data2.dropna()

data2_modified.to_csv("modifiedData2.csv", index=False)


df_2=pd.read_csv("modifiedData2.csv")

print(df_2[0:6])

print(df_2['result'])

df_main2=df_2[df_2.columns[~df_2.columns.isin(['text', 'user_name'])]]

print(df_main2.columns)

print(len(df_main2.columns))

  

X_2=df_main2[df_main2.columns[~df_main2.columns.isin(['time', 'tweet_id','result'])]] #removing result attribute as it is class label, hence we get 34 attributes
X_2=X_2.iloc[:,1:len(X_2.columns)].values   #removing the unnamed attribute
x_2=df_main2[df_main2.columns[~df_main2.columns.isin(['time', 'tweet_id','result'])]]
x_2=x_2.iloc[:,1:len(x_2.columns)].values 
y_2=df_main2.loc[:, ['result']].values


print(type(X_2), type(y_2), type(x_2), type(y_2))

print(X_2.shape)
print(y_2.shape)

Data Shape: (3004, 38)
   Unnamed: 0  cat1  cat10  ...             tweet_id  url      user_name
0           0     0      0  ...  1155575657402961920    1  THEJEROMEOWEN
1           1     0      0  ...  1155459426243043328    0  THEJEROMEOWEN
2           2     0      0  ...  1126969730307448832    0     rabrakha14
3           3     0      0  ...  1155277550794338304    0       RS_Aloha
4           4     0      0  ...  1155188179395207168    0       RS_Aloha

[5 rows x 38 columns]
   Unnamed: 0  cat1  cat10  ...             tweet_id  url      user_name
0           0     0      0  ...  1155575657402961920    1  THEJEROMEOWEN
1           1     0      0  ...  1155459426243043328    0  THEJEROMEOWEN
2           2     0      0  ...  1126969730307448832    0     rabrakha14
3           3     0      0  ...  1155277550794338304    0       RS_Aloha
4           4     0      0  ...  1155188179395207168    0       RS_Aloha
5           5     0      0  ...  1154962871765393408    0  preciselyizzy

[6 r

In [0]:
import pandas as pd
import numpy as np

df_h=pd.read_csv(url_h)

print(df_h.columns)


'''
the following way is wrong
label1=df_h.heuristic1.values
label_1=df_h.heuristic1_1.values
label2=df_h.heuristic2.values
label3=df_h.heuristic3.values

print(type(label1), type(label2), type(label3))



print(type(label1), type(label2), type(label3))

print(y_1.shape, label1.shape, label2.shape, label3.shape)

#print(len(label1),len(label2),len(label3), len(label_1))

'''




label1=df_h.loc[:, ['heuristic1']].values
label_1=df_h.loc[:,['heuristic1_1']].values
label2=df_h.loc[:, ['heuristic2']].values
label3=df_h.loc[:, ['heuristic3']].values

print(type(label1), type(label2), type(label3))



print(type(label1), type(label2), type(label3))

print(y_1.shape, label1.shape, label2.shape, label3.shape)


tem1y=np.append(y_1, label1, axis=0)
tem2y=np.append(y_1, label2, axis=0)
tem3y=np.append(y_1, label3, axis=0)

tem_1y=np.append(y_1, label_1, axis=0)

T_h1=torch.from_numpy(tem1y)
T_h2=torch.from_numpy(tem2y)
T_h3=torch.from_numpy(tem3y)
T_h_1=torch.from_numpy(tem_1y)


Index(['Unnamed: 0', 'heuristic1', 'heuristic1_1', 'heuristic2', 'heuristic3'], dtype='object')
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
(1906, 1) (3273, 1) (3273, 1) (3273, 1)


In [0]:
#Appending present and previosu data with actual label data...

tem=np.append(X_1, X_2, axis=0)
tem_y=np.append(y_1,label1,axis=0)
print(X_1.shape, X_2.shape, tem.shape)
print(y_1.shape, y_2.shape, tem_y.shape)

X=tem
T=tem_y

print(X.shape, T.shape)

print(type(X_1))
#convert to tensor
X = torch.from_numpy(X)
T = torch.from_numpy(T)

X_1 = torch.from_numpy(X_1)
T_1 = torch.from_numpy(y_1)

X_2 = torch.from_numpy(X_2)
T_2 = torch.from_numpy(y_2)

print(type(X), type(T))

(1906, 34) (3004, 34) (4910, 34)
(1906, 1) (3004, 1) (5179, 1)
(4910, 34) (5179, 1)
<class 'numpy.ndarray'>
<class 'torch.Tensor'> <class 'torch.Tensor'>


In [0]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler
import torch.nn.functional as F

## create training and validation split 
split_size = int(0.8 * len(X_1))
index_list = list(range(len(X_1)))
train_idx, valid_idx = index_list[:split_size], index_list[split_size:]





'''
x_tr = torch.tensor(X[train_idx], dtype=torch.long)
y_tr = torch.tensor(T[train_idx], dtype=torch.float32)
train = TensorDataset(x_tr, y_tr)
trainloader = DataLoader(train, batch_size=128)
'''

x_tr = torch.tensor(X_1[train_idx], dtype=torch.long)
y_tr = torch.tensor(T_1[train_idx], dtype=torch.float32)
train = TensorDataset(x_tr, y_tr)
trainloader = DataLoader(train, batch_size=128)

x_valid = torch.tensor(X_1[valid_idx], dtype=torch.long)
y_valid = torch.tensor(T_1[valid_idx], dtype=torch.float32)
valid = TensorDataset(x_valid, y_valid)
validloader = DataLoader(valid, batch_size=128)

x_tr2 = torch.tensor(X_2[train_idx], dtype=torch.long)
y_tr2 = torch.tensor(T_2[train_idx], dtype=torch.float32)
train2 = TensorDataset(x_tr2, y_tr2)
trainloader2 = DataLoader(train2, batch_size=128)



##Following is Auxiliary data set


split_size = int(0.8 * len(X_2))
index_list = list(range(len(X_2)))
train_idx, valid_idx = index_list[:split_size], index_list[split_size:]


x_tr2 = torch.tensor(X_2[train_idx], dtype=torch.long)
y_tr2 = torch.tensor(T_2[train_idx], dtype=torch.float32)
train2 = TensorDataset(x_tr2, y_tr2)
trainloader2 = DataLoader(train2, batch_size=128)

x_valid2 = torch.tensor(X_2[valid_idx], dtype=torch.long)
y_valid2 = torch.tensor(T_2[valid_idx], dtype=torch.float32)
valid2 = TensorDataset(x_valid2, y_valid2)
validloader = DataLoader(valid2, batch_size=128)



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:23: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:27: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:28: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(Tru

In [0]:
##Concatenating the tensors

import torch as pytorch

pytorch.set_default_tensor_type('torch.DoubleTensor')

X_1=X_1.type(torch.DoubleTensor)
T_1=T_1.type(torch.DoubleTensor)

X_2=X_2.type(torch.DoubleTensor)
T_2=T_2.type(torch.DoubleTensor)


X=torch.cat((X_1,X_2), 0)

print(X.shape)

X_tr=torch.cat((x_tr,x_tr2),0)

print(X_tr.shape)

Y_tr=torch.cat((y_tr,y_tr2),0)  ##y_tr2 doesn't have values, we should calculate using heuristics

X_valid=torch.cat((x_valid,x_valid2),0)

Y_valid=torch.cat((y_valid,y_valid2),0)

Train=TensorDataset(X_tr, Y_tr)
TrainLoader=DataLoader(Train, batch_size=128)


Valid=TensorDataset(X_valid, Y_valid)
ValidLoader=DataLoader(Valid, batch_size=128)


print(X_tr.type())

X_tr=torch.tensor(X_tr, dtype=torch.double)

X_valid=torch.tensor(X_valid, dtype=torch.double)

print(X_tr.type(), X_valid.type())

torch.Size([4910, 34])
torch.Size([3927, 34])
torch.LongTensor
torch.DoubleTensor torch.DoubleTensor


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:37: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:39: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


In [0]:
batch_size = 50
n_iters = 3000
epochs = n_iters / (len(X_1) / batch_size)
epochs2= n_iters / (len(X_2) / batch_size)
#epochs= n_iters/((len(X_1)+len(X_2))/batch_size)
input_dim = 34
output_dim = 2
lr_rate = 0.001

class LogisticRegression(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LogisticRegression, self).__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim)
        #self.linear = torch.nn.Linear(2*input_dim, output_dim)

    def forward(self, x):
        outputs = self.linear(x)
        return outputs


In [0]:
model=LogisticRegression(input_dim, output_dim)
print(type(model.parameters()))
print(model.parameters())
#a=model.parameters()
#len(a)

model.parameters

<class 'generator'>
<generator object Module.parameters at 0x7eff1cd101a8>


<bound method Module.parameters of LogisticRegression(
  (linear): Linear(in_features=34, out_features=2, bias=True)
)>

In [0]:
model = LogisticRegression(input_dim, output_dim)

criterion = torch.nn.CrossEntropyLoss() # computes softmax and then the cross entropy

optimizer = torch.optim.SGD(model.parameters(), lr=lr_rate)



print("\n initialized_weights = \n")
for param in model.parameters():
  print(param.data)

##Training the data
iterations = 0
for epoch in range(int(epochs)):
    for i, (data_X, labels) in enumerate(trainloader):
        data_X = Variable(data_X.view(-1,34))
        labels = Variable(labels)
        labels=torch.tensor(labels, dtype=torch.long)
        #print(labels.__class__)

        optimizer.zero_grad()
        data_X=torch.tensor(data_X, dtype=torch.double)
        #print(data_X.shape, data_X.type())
        
        outputs = model(data_X)
        labels = labels.squeeze_()
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        iterations+=1
        if iterations%100==0:
            # calculate Accuracy
            correct = 0
            total = 0
            for data_X, labels in validloader:
                data_X = Variable(data_X.view(-1, 34))
                
                data_X=torch.tensor(data_X, dtype=torch.double)
                labels=torch.tensor(labels, dtype=torch.long)
                
                outputs = model(data_X)
                _, predicted = torch.max(outputs.data, 1)
                total+= labels.size(0)
                # for gpu, bring the predicted and labels back to cpu fro python operations to work
                pr=predicted.numpy()
                lb=labels.numpy()
                for i in range(len(pr)):
                  if(pr[i]==lb[i]):
                    correct = correct+ 1
                    
                #correct+= (predicted == labels).sum()
            accuracy = 100 * correct/total
            print("Iteration: {}. Loss: {}.Correct:{}. total:{}. Accuracy: {}.".format(iterations, loss.item(), correct, total,  accuracy))


 initialized_weights = 

tensor([[-0.0676, -0.1260,  0.0526,  0.1464,  0.1325, -0.0564, -0.1504, -0.1577,
         -0.0495,  0.0622,  0.0943, -0.0065,  0.0794, -0.0835, -0.0358,  0.1701,
          0.0465,  0.0534,  0.1311, -0.1391,  0.0465,  0.0162, -0.0891, -0.1459,
          0.1162, -0.0299,  0.0167, -0.1588, -0.0775,  0.0043, -0.1480, -0.0437,
         -0.1109, -0.0924],
        [ 0.1554, -0.0416,  0.1660,  0.0476,  0.1376,  0.0724,  0.0585, -0.1386,
          0.0809, -0.1118,  0.1696,  0.0470, -0.0844, -0.0120, -0.0332,  0.1185,
          0.1045,  0.1550,  0.1071, -0.0093, -0.0762, -0.1704,  0.0292, -0.0303,
          0.1682, -0.1494,  0.0132,  0.0129, -0.1192, -0.1583, -0.1067,  0.0011,
         -0.1330,  0.1458]])
tensor([ 0.0963, -0.1502])
Iteration: 100. Loss: 0.6606340579818804.Correct:60. total:601. Accuracy: 9.983361064891847.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:23: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:40: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:41: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(Tru

Iteration: 200. Loss: 1.0300618264382555.Correct:49. total:601. Accuracy: 8.153078202995008.
Iteration: 300. Loss: 0.7037779200863574.Correct:256. total:601. Accuracy: 42.59567387687188.
Iteration: 400. Loss: 0.6043031077201624.Correct:60. total:601. Accuracy: 9.983361064891847.
Iteration: 500. Loss: 1.0021704215832103.Correct:49. total:601. Accuracy: 8.153078202995008.
Iteration: 600. Loss: 0.7060358867314738.Correct:248. total:601. Accuracy: 41.26455906821963.
Iteration: 700. Loss: 0.5690994990825968.Correct:64. total:601. Accuracy: 10.64891846921797.
Iteration: 800. Loss: 0.9819999864546076.Correct:51. total:601. Accuracy: 8.48585690515807.
Iteration: 900. Loss: 0.7037637028924731.Correct:260. total:601. Accuracy: 43.261231281198.


In [0]:
## For output dim=1 of above model

batch_size = 50
n_iters = 3000
epochs = n_iters / (len(X_1) / batch_size)
epochs2= n_iters / (len(X_2) / batch_size)
#epochs= n_iters/((len(X_1)+len(X_2))/batch_size)
input_dim = 34
output_dim = 1
lr_rate = 0.001

class LogisticRegression(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LogisticRegression, self).__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim)
        #self.linear = torch.nn.Linear(2*input_dim, output_dim)

    def forward(self, x):
        outputs = self.linear(x)
        return outputs

      
      
model=LogisticRegression(input_dim, output_dim)
print(type(model.parameters()))
print(model.parameters())
#a=model.parameters()
#len(a)

model.parameters


model = LogisticRegression(input_dim, output_dim)

criterion = torch.nn.CrossEntropyLoss() # computes softmax and then the cross entropy

optimizer = torch.optim.SGD(model.parameters(), lr=lr_rate)



print("\n initialized_weights = \n")
for param in model.parameters():
  print(param.data)

##Training the data
iterations = 0
for epoch in range(int(epochs)):
    for i, (data_X, labels) in enumerate(trainloader):
        data_X = Variable(data_X.view(-1,34))
        labels = Variable(labels)
        labels=torch.tensor(labels, dtype=torch.long)
        #print(labels.__class__)

        optimizer.zero_grad()
        data_X=torch.tensor(data_X, dtype=torch.double)
        #print(data_X.shape, data_X.type())
        
        outputs = model(data_X)
        labels = labels.squeeze_()
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        iterations+=1
        if iterations%100==0:
            # calculate Accuracy
            correct = 0
            total = 0
            for data_X, labels in validloader:
                data_X = Variable(data_X.view(-1, 34))
                
                data_X=torch.tensor(data_X, dtype=torch.double)
                labels=torch.tensor(labels, dtype=torch.long)
                
                outputs = model(data_X)
                _, predicted = torch.max(outputs.data, 1)
                total+= labels.size(0)
                # for gpu, bring the predicted and labels back to cpu fro python operations to work
                pr=predicted.numpy()
                lb=labels.numpy()
                for i in range(len(pr)):
                  if(pr[i]==lb[i]):
                    correct = correct+ 1
                    
                #correct+= (predicted == labels).sum()
            accuracy = 100 * correct/total
            print("Iteration: {}. Loss: {}.Correct:{}. total:{}. Accuracy: {}.".format(iterations, loss.item(), correct, total,  accuracy))

<class 'generator'>
<generator object Module.parameters at 0x7eff1ccf2bf8>

 initialized_weights = 

tensor([[ 0.1079, -0.0839, -0.1499, -0.0033, -0.1619,  0.1377,  0.1373,  0.0874,
         -0.0007,  0.1163,  0.1513, -0.0178, -0.0520,  0.0970, -0.1445,  0.0428,
         -0.1599,  0.0243,  0.1554,  0.0763, -0.0721,  0.0701, -0.1652, -0.1081,
         -0.0221,  0.1663, -0.1363, -0.0385, -0.0802,  0.1448, -0.1238,  0.0817,
          0.0213, -0.0944]])
tensor([0.0998])


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:50: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:54: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


RuntimeError: ignored

In [0]:
#####Using different weights for previous tweets and defining loss via adding different forward function

batch_size = 50
n_iters = 3000
epochs = n_iters / (len(X_1) / batch_size)
epochs2= n_iters / (len(X_2) / batch_size)
#epochs= n_iters/((len(X_1)+len(X_2))/batch_size)
input_dim = 34
output_dim = 2
lr_rate = 0.001

class LogisticRegression(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LogisticRegression, self).__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim)
        #self.linear = torch.nn.Linear(2*input_dim, output_dim)

    def forward(self, x1, x2):
        out1 = self.linear(x1)
        out2 = self.linear(x2)
        outputs=(out1+out2)/2
        return outputs


In [0]:
import torch as pytorch
import numpy as np

pytorch.set_default_tensor_type('torch.DoubleTensor')

X_1=X_1.type(torch.DoubleTensor)
T_1=T_1.type(torch.DoubleTensor)


X_2=X_2.type(torch.DoubleTensor)
T_2=T_2.type(torch.DoubleTensor)

W = Variable(torch.randn(1, 34, dtype=torch.double), requires_grad=True)
b = Variable(torch.randn(1, 1, dtype=torch.double), requires_grad=True)
print(W.size())

#Weights for Previoes tweets
#W1 = Variable(torch.randn(1, 34, dtype=torch.double), requires_grad=True)
#W_p = Variable(torch.randn(1, 34, dtype=torch.double), requires_grad=True)
#W_p=W_p.type(torch.LongTensor)
#b_p = Variable(torch.randn(1, 1, dtype=torch.double), requires_grad=True)
#print(W_p.size(), torch.Tensor(W_p).dtype)
#print(W.size(), torch.Tensor(W_p).dtype)


#sigmoid
def sigmoid(x):
    return 1/(1+torch.exp(-x))

#out = sigmoid(torch.mm(X, W.view(34,1))+b)

out_present= sigmoid(torch.mm(X_1, W.view(34,1))+b)

#out_prev= sigmoid(torch.mm(X_2, W_p.view(34,1))+b_p)
out_prev_same_weight=sigmoid(torch.mm(X_2,W.view(34,1))+b)

'''

def my_loss(out1, target1, out2, target2,cnt):
  print(out1.type(),len(out1), target1.type() ,out2.type(),len(out2), target2.type())
  target1=target1.numpy()
  target2=target2.numpy()
  #out1=out1.numpy(), we can't call numpy on out1 and out2 because we can't call numpy on var that require grad
  #out2=out2.numpy()
  print("\n After numpy conversion \n", len(target1), len(target2))
  
  l1=-target1 * torch.log(out1) - (1-target1) * torch.log(1-out1)
  
  #print(target1.type(), out1.type())
  l2=-target2 * torch.log(out2) - (1-target2) * torch.log(1-out2)
  
  return torch.tensor(np.mean(l1+l2))
  
'''
  
  
def my_loss(out1, target1, out2, target2):
  target1=torch.tensor(target1, dtype=torch.double)
  target2=torch.tensor(target2, dtype=torch.double)

  
  #print(out1.type(),len(out1), target1.type(),len(target1) ,out2.type(),len(out2), target2.type(),len(target2))
  l1=-target1 * torch.log(out1) - (1-target1) * torch.log(1-out1)
  
  #print(target1.type(), out1.type())
  l2=-target2 * torch.log(out2) - (1-target2) * torch.log(1-out2)
  return torch.mean(l1+l2)
  return l1+l2

  

torch.Size([1, 34])


In [0]:
model = LogisticRegression(input_dim, output_dim)

criterion = torch.nn.CrossEntropyLoss() # computes softmax and then the cross entropy

optimizer = torch.optim.SGD(model.parameters(), lr=lr_rate)


for param in model.parameters():
  print("\n", param.data)

##Training the data
iterations = 0
for epoch in range(int(epochs)):
    cnt=0
    print_cnt=1
    for  (data_X, labels,x2,y2) in zip(x_tr,y_tr,x_tr2,y_tr2):
        data_X = Variable(data_X.view(-1,34))
        labels = Variable(labels)
        
        x2 = Variable(data_X.view(-1,34))
        y2 = Variable(y2)
        
        data_X=torch.tensor(data_X, dtype=torch.double)
        labels=torch.tensor(labels, dtype=torch.long)
        
        x2=torch.tensor(x2,dtype=torch.double)
        y2=torch.tensor(y2,dtype=torch.long)
        
       
        #print(labels.__class__)

        optimizer.zero_grad()
        
        #print(data_X.shape, data_X.type())
        
        outputs = model(data_X)
        labels = labels.squeeze_()
        
        out1=model(data_X)
        out2=model(x2)
        
        #label_val=torch.tensor(labels[cnt])
        #y2_val=torch.tensor(y2[cnt])
        
        y2=y2.squeeze_()
        #loss = criterion(outputs, labels)
        #loss=my_loss(out1,label_val,out2,y2_val)
        #loss=my_loss(out1,labels,out2,y2,cnt)
        loss=my_loss(out1,labels,out2,y2)
        loss.backward()
        optimizer.step()
        
        cnt+=1

        #iterations+=1
        
        if iterations%10==0 and print_cnt==1:
            print_cnt=0
            # calculate Accuracy
            correct = 0
            total = 0
            for data_X, labels,x2,y2 in zip(x_valid,y_valid, x_valid2,y_valid2):
                data_X = Variable(data_X.view(-1, 34))
                
                data_X=torch.tensor(data_X, dtype=torch.double)
                labels=torch.tensor(labels, dtype=torch.long)
                
                x2 = Variable(data_X.view(-1,34))
                y2 = Variable(y2)
                
                x2=torch.tensor(x2,dtype=torch.double)
                y2=torch.tensor(y2, dtype=torch.long)
                
                outputs = model(data_X)
                _, predicted = torch.max(outputs.data, 1)
                total+= labels.size(0)
                # for gpu, bring the predicted and labels back to cpu fro python operations to work
                pr=predicted.numpy()
                lb=labels.numpy()
                for i in range(len(pr)):
                  if(pr[i]==lb[i]):
                    correct = correct+ 1
                    
                #correct+= (predicted == labels).sum()
                
            #iterations+=1
            accuracy = 100 * correct/total
            print("Iteration: {}. Loss: {}.Correct:{}. total:{}. Accuracy: {}.".format(iterations, loss.item(), correct, total,  accuracy))
       
    iterations+=1


 tensor([[-0.0967, -0.1131,  0.1547, -0.1049,  0.0389, -0.0262,  0.0479,  0.0782,
          0.0131, -0.1127, -0.0521,  0.0997, -0.0067,  0.0571,  0.0448, -0.0665,
          0.1008, -0.0876,  0.1350,  0.0513,  0.0555, -0.1171, -0.0818, -0.1276,
         -0.0125, -0.0328,  0.0354, -0.0660, -0.1319,  0.0002,  0.0743,  0.1331,
          0.0225,  0.0970],
        [ 0.0827, -0.1100,  0.1147, -0.0378, -0.1213, -0.0037,  0.0196, -0.1361,
          0.1561, -0.0331,  0.0005, -0.0352,  0.0591,  0.1045,  0.0053,  0.0299,
          0.1678, -0.0411, -0.0481, -0.0484,  0.1273,  0.1627,  0.0127,  0.0643,
          0.0254, -0.1005,  0.0228, -0.0644, -0.1644, -0.0429, -0.1133,  0.0151,
          0.0835,  0.1594]])

 tensor([-0.1383, -0.1448])
Iteration: 0. Loss: nan.Correct:361. total:382. Accuracy: 94.50261780104712.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:23: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:24: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:26: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:27: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(Tru

Iteration: 10. Loss: nan.Correct:382. total:382. Accuracy: 100.0.
Iteration: 20. Loss: nan.Correct:382. total:382. Accuracy: 100.0.
Iteration: 30. Loss: nan.Correct:382. total:382. Accuracy: 100.0.
Iteration: 40. Loss: nan.Correct:382. total:382. Accuracy: 100.0.
Iteration: 50. Loss: nan.Correct:382. total:382. Accuracy: 100.0.
Iteration: 60. Loss: nan.Correct:382. total:382. Accuracy: 100.0.
Iteration: 70. Loss: nan.Correct:382. total:382. Accuracy: 100.0.


In [0]:
for epoch in range(int(epochs/5)):
  print(epoch)