<a href="https://colab.research.google.com/github/Prakface/Practice/blob/master/ApplyingExisting1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Logistic Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
url='https://raw.githubusercontent.com/Prakface/Practice/master/initialFeatures.csv'

data=pd.read_csv(url)


print(data.isnull())

#the follwoing line is used to remove null valued rows, but the index of rows still corresponds to old one , loses serial order
data_modified= data.dropna()   


#print(data_modified)


#to arrange rows in serial order which are left in file, storeback modified data frame to a csv file and again read this new csv file into a data frame



data_modified.to_csv("modifiedData.csv", index=False)



df2=pd.read_csv("modifiedData.csv")

#df2


dataset = df2.drop("level", axis = 1)
data_X = dataset.iloc[:, 0:27].values
data_y = dataset.iloc[:, 27].values
from sklearn.utils import shuffle
dataset = shuffle(dataset, random_state=0)









       image    url  question  original  ...  retweets_count   hour  level  result
0      False  False     False     False  ...           False  False  False   False
1       True   True      True      True  ...            True   True   True    True
2      False  False     False     False  ...           False  False  False   False
3       True   True      True      True  ...            True   True   True    True
4      False  False     False     False  ...           False  False  False   False
5       True   True      True      True  ...            True   True   True    True
6      False  False     False     False  ...           False  False  False   False
7       True   True      True      True  ...            True   True   True    True
8      False  False     False     False  ...           False  False  False   False
9       True   True      True      True  ...            True   True   True    True
10     False  False     False     False  ...           False  False  False   False
11  

In [2]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_X, data_y, test_size = 0.35, random_state = 0)

# Feature Scaling
'''from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)'''



'from sklearn.preprocessing import StandardScaler\nsc = StandardScaler()\nX_train = sc.fit_transform(X_train)\nX_test = sc.transform(X_test)'

In [3]:
#For kernel SVM

from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score


print("\n for svm with rbf kernel \n ")
clf = SVC(kernel = 'rbf', gamma=0.1)
#clf.fit(X_train, y_train)

#clf2 = SVC(kernel='linear', C=1, random_state=0)

# cross_validate without scoring parameter computes accuracy for each fold
scores = cross_val_score(clf, data_X, data_y,cv=5)
#sorted(scores.keys())
print("\n accuracy scores = ", scores)

#for finding F1 measure at each fold, use scoring marameter in cross_validate
scores = cross_val_score(clf, data_X, data_y, scoring='f1_macro',cv=10)

print("F1 measure values  = ", scores)


clf.fit(X_train, y_train)
# Predicting the Test set results
y_pred = clf.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)




 for svm with rbf kernel 
 

 accuracy scores =  [0.58212766 0.64680851 0.78553191 0.64851064 0.6       ]
F1 measure values  =  [0.54009794 0.59472466 0.58013145 0.68516129 0.7967248  0.8044294
 0.62853278 0.57716644 0.62895855 0.51426712]
[[587 406]
 [203 861]]


In [0]:
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score
scoring = ['precision_macro', 'recall_macro']
clf = SVC(kernel='linear', C=1, random_state=0)
scores = cross_validate(clf, data_X, data_y, scoring=scoring,cv=5)
sorted(scores.keys())

In [0]:
from sklearn.model_selection import cross_val_score
print('\n for svm with linear  kernel \n')
clf = SVC(kernel='linear',degree=2, C=1, random_state=0)

# cross_validate without scoring parameter computes accuracy for each fold
scores = cross_val_score(clf, data_X, data_y,cv=5)
sorted(scores.keys())
print("\n accuracy scores = ", scores)

#for finding F1 measure at each fold, use scoring marameter in cross_validate
scores = cross_val_score(clf, data_X, data_y, scoring='f1_macro',cv=5)
sorted(scores.keys())

print("F1 measure values  = ", scores)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)


 for svm with linear  kernel 



In [10]:
#For random logistic regression

from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score
scoring = ['accuracy', 'f1_macro', 'precision_macro', 'recall_macro']


clf = LogisticRegression(random_state = 0)

scores = cross_validate(clf, data_X, data_y, scoring=scoring,cv=5)

print(sorted(scores.keys()))
print(scores)

clf.fit(X_train, y_train)


# Predicting the Test set results
y_pred = clf.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


['fit_time', 'score_time', 'test_accuracy', 'test_f1_macro', 'test_precision_macro', 'test_recall_macro']
{'fit_time': array([0.0479126 , 0.06289649, 0.05467796, 0.05020976, 0.06265092]), 'score_time': array([0.00675511, 0.00613666, 0.00608897, 0.00621486, 0.0061245 ]), 'test_accuracy': array([0.59829787, 0.65361702, 0.76085106, 0.68510638, 0.61617021]), 'test_f1_macro': array([0.59001609, 0.65032549, 0.75931065, 0.68451203, 0.60115261]), 'test_precision_macro': array([0.6013516 , 0.65557128, 0.77315541, 0.68491944, 0.62765957]), 'test_recall_macro': array([0.59477534, 0.65140598, 0.76370026, 0.68442723, 0.61120261])}
[[633 360]
 [319 745]]


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [11]:
#For random forest classification

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
clf.fit(X_train, y_train)


scoring = ['accuracy', 'f1_macro', 'precision_macro', 'recall_macro']

scores = cross_validate(clf, data_X, data_y, scoring=scoring,cv=5)

print(sorted(scores.keys()))
print(scores)

clf.fit(X_train, y_train)


# Predicting the Test set results
y_pred = clf.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)



['fit_time', 'score_time', 'test_accuracy', 'test_f1_macro', 'test_precision_macro', 'test_recall_macro']
{'fit_time': array([0.69493699, 0.69797015, 0.748034  , 0.71075368, 0.69443488]), 'score_time': array([0.14346957, 0.13667679, 0.12841725, 0.13517809, 0.13986397]), 'test_accuracy': array([0.64085106, 0.66723404, 0.78297872, 0.7012766 , 0.65191489]), 'test_f1_macro': array([0.63212164, 0.66439877, 0.78244864, 0.70126881, 0.64373905]), 'test_precision_macro': array([0.64856678, 0.66914996, 0.78941332, 0.70159196, 0.6601572 ]), 'test_recall_macro': array([0.63702723, 0.66517728, 0.78498423, 0.70168665, 0.64817156])}
[[645 348]
 [253 811]]


In [0]:
# Visualising the Training set results
'''from matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Logistic Regression (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

# Visualising the Test set results
from matplotlib.colors import ListedColormap
X_set, y_set = X_test, y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Logistic Regression (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()'''


ValueError: ignored

In [0]:
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

from sklearn import svm
from sklearn import datasets

iris=datasets.load_iris()

scoring = ['precision_macro', 'recall_macro']
clf = svm.SVC(kernel='linear', C=1, random_state=0)
scores = cross_validate(clf, iris.data, iris.target, scoring=scoring,cv=5)
sorted(scores.keys())
#['fit_time', 'score_time', 'test_precision_macro', 'test_recall_macro']

print(scores['test_recall_macro'])

scores['test_recall_macro']


print(scores['test_precision_macro'])
scores['test_precision_macro']


print(scores['score_time'])
scores['score_time']


print(scores.keys())



#print(iris)

[0.96666667 1.         0.96666667 0.96666667 1.        ]
[0.96969697 1.         0.96969697 0.96969697 1.        ]
[0.00862432 0.00144005 0.00157189 0.00169373 0.00168037]
dict_keys(['fit_time', 'score_time', 'test_precision_macro', 'test_recall_macro'])


In [0]:
df2[]